<?xml version="1.0" ?><!DOCTYPE TS><TS language="de" sourcelanguage="en" version="2.1">
<context>
    <name/>
    <message id="libintfuorit-err-net-reply-1">
        <source>The remote server at %1 refused the connection.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-2">
        <source>The remote server at %1 closed the connection prematurely, before the entire reply was received and processed.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-3">
        <source>The remote host name %1 was not found.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-4">
        <source>The connection to the server at %1 timed out.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-5">
        <source>The operation was canceled before it was finished.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-6">
        <source>The SSL/TLS handshake failed and the encrypted channel could not be established.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-7">
        <source>The connection was broken due to disconnection from the network.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-8">
        <source>The connection was broken due to disconnection from the network or failure to start the network.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-9">
        <source>The background request is not currently allowed due to platform policy.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-10">
        <source>While following redirects, the maximum limit was reached.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-11">
        <source>While following redirects, the network access API detected a redirect from an encrypted protocol (https) to an unencrypted one (http).</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-101">
        <source>The connection to the proxy server was refused (the proxy server is not accepting requests).</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-102">
        <source>The proxy server closed the connection prematurely, before the entire reply was received and processed.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-103">
        <source>The proxy host name was not found (invalid proxy hostname).</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-104">
        <source>The connection to the proxy timed out or the proxy did not reply in time to the request sent</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-105">
        <source>The proxy requires authentication in order to honour the request but did not accept any credentials offered (if any).</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-201">
        <source>The access to the remote content was denied.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-202">
        <source>The operation requested on the remote content is not permitted.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-203">
        <source>The remote content was not found at the server.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-204">
        <source>The remote server requires authentication to serve the content but the credentials provided were not accepted (if any).</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-205">
        <source>The request needed to be sent again, but this failed for example because the upload data could not be read a second time.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-206">
        <source>The request could not be completed due to a conflict with the current state of the resource.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-207">
        <source>The requested resource is no longer available at the server.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-401">
        <source>The server encountered an unexpected condition which prevented it from fulfilling the request.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-402">
        <source>The server does not support the functionality required to fulfill the request.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-403">
        <source>The server is unable to handle the request at this time.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-301">
        <source>The Network Access API cannot honor the request because the protocol is not known.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-302">
        <source>The requested operation is invalid for this protocol.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-99">
        <source>An unknown network-related error was detected.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-199">
        <source>An unknown proxy-related error was detected.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-299">
        <source>An unknown error related to the remote content was detected.</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-399">
        <source>A breakdown in protocol was detected (parsing error, invalid or unexpected responses, etc.).</source>
        <translation type="unfinished"/>
    </message>
    <message id="libintfuorit-err-net-reply-499">
        <source>An unknown error related to the server response was detected.</source>
        <translation type="unfinished"/>
    </message>
</context>
</TS>